bokuweb/docx-rs

- Cargo.lock
- docx-core/src/documents/elements/comment.rs
- docx-core/src/documents/elements/level.rs
- docx-core/src/documents/elements/paragraph.rs
- docx-core/src/documents/elements/run.rs
- docx-core/src/documents/elements/table.rs
- docx-core/src/documents/elements/table_cell.rs
- docx-core/src/documents/elements/table_row.rs
- docx-core/src/documents/mod.rs
- docx-core/src/types/special_indent_type.rs
- docx-wasm/Cargo.toml
- docx-wasm/index.js
- docx-wasm/src/adaptors/mod.rs
- docx-wasm/src/adaptors/special_indent.rs
- docx-wasm/src/comment.rs
- docx-wasm/src/delete.rs
- docx-wasm/src/docx.rs
- docx-wasm/src/insert.rs
- docx-wasm/src/level.rs
- docx-wasm/src/lib.rs
- docx-wasm/src/numbering.rs
- docx-wasm/src/paragraph.rs
- docx-wasm/src/run.rs
- docx-wasm/src/table.rs
- docx-wasm/src/table_cell.rs
- docx-wasm/src/table_row.rs
> Prepare for wasm

- docx-core/src/documents/elements/table.rs
- docx-wasm/src/table.rs
> feat: Support table width

- docx-core/src/documents/doc_props/core.rs
- docx-core/src/documents/doc_props/mod.rs
- docx-core/src/documents/mod.rs
- docx-core/tests/lib.rs
> feat: Support date

- docx-core/src/documents/document.rs
- docx-core/src/documents/elements/paragraph.rs
- docx-core/src/documents/elements/table.rs
- docx-core/src/documents/elements/table_cell.rs
- docx-core/src/documents/elements/table_row.rs
- docx-core/src/documents/mod.rs
- docx-core/src/documents/numberings.rs
- docx-core/tests/lib.rs
> fix: numbering error on word online

- docx-core/src/documents/elements/delete.rs
- docx-core/src/documents/elements/insert.rs
- docx-core/tests/lib.rs
- docx-wasm/src/delete.rs
- docx-wasm/src/insert.rs
> fix: Add run, author and date to insert and delete

- .github/workflows/ci.yml
> fix:ci.yaml

- README.md
- docx-core/examples/alignment.rs
- docx-core/examples/comment.rs
- docx-core/examples/hello.rs
- docx-core/examples/history.rs
- docx-core/examples/indent.rs
- docx-core/examples/numbering.rs
- docx-core/examples/table.rs
- docx-core/tests/lib.rs
> chore: Add examples

- docx-wasm/example/index.ts
- docx-wasm/js/index.ts
- docx-wasm/js/run.ts
- docx-wasm/js/table-cell.ts
- docx-wasm/js/table.ts
- docx-wasm/package.json
- docx-wasm/tsconfig.json
> Fix run props

- docx-wasm/js/index.ts
- docx-wasm/package.json
- docx-wasm/pkg/package.json
> Fix delete

- docx-core/examples/numbering.rs
- docx-core/src/documents/elements/abstract_numbering.rs
- docx-core/src/documents/elements/mod.rs
- docx-core/src/documents/elements/numbering.rs
- docx-core/src/documents/mod.rs
- docx-core/src/documents/numberings.rs
- docx-core/tests/lib.rs
- docx-wasm/js/abstract-numbering.ts
- docx-wasm/js/index.ts
- docx-wasm/js/numbering.ts
- docx-wasm/src/abstract_numbering.rs
- docx-wasm/src/doc.rs
- docx-wasm/src/lib.rs
- docx-wasm/src/numbering.rs
- fixtures/paragraph/word/numbering.xml
> fix: add abstract numbering and numbering

- docx-core/src/documents/elements/style.rs
- docx-core/src/documents/styles.rs
- docx-core/src/reader/attributes/indent.rs
- docx-core/src/reader/attributes/mod.rs
- docx-core/src/reader/mod.rs
- docx-core/src/reader/paragraph.rs
- docx-core/src/reader/style.rs
- docx-core/src/reader/styles.rs
- docx-core/src/reader/xml_element.rs
- docx-core/src/types/style_type.rs
- fixtures/table_merged_libre_office/word/styles.xml
> feat: style reader

- docx-core/examples/reader.rs
- docx-core/src/reader/errors.rs
- docx-core/src/reader/mod.rs
- docx-wasm/js/index.ts
- docx-wasm/package.json
- docx-wasm/src/reader.rs
> Update npm pkg

- docx-wasm/js/json/index.ts
- docx-wasm/js/json/numbering.ts
> feat: Add definition

- docx-wasm/js/json/indent.ts
- docx-wasm/js/json/index.ts
- docx-wasm/js/json/numbering.ts
- docx-wasm/js/json/paragraph.ts
- docx-wasm/js/json/styles.ts
- docx-wasm/package.json
> fix: indent

- docx-core/examples/reader.rs
- docx-core/src/reader/run.rs
- docx-wasm/package.json
> Fix breaking

- docx-core/src/reader/run.rs
- docx-wasm/package.json
> fix: bold and italic

- docx-core/examples/reader.rs
- docx-core/src/documents/elements/numbering_property.rs
- docx-core/src/documents/elements/paragraph_property.rs
- docx-core/src/reader/numbering_property.rs
- docx-core/src/reader/paragraph.rs
- docx-wasm/js/json/paragraph.ts
- docx-wasm/package.json
> Fix reader error2

- docx-wasm/js/json/numbering.ts
- docx-wasm/package.json
> Fix json num types

- docx-core/examples/table_border.rs
- docx-core/src/documents/elements/table_cell.rs
- docx-core/src/documents/elements/table_cell_borders.rs
- docx-core/src/documents/elements/table_cell_property.rs
- docx-core/src/reader/mod.rs
- docx-core/src/reader/read_zip.rs
- docx-core/src/types/border_position.rs
- docx-core/src/types/border_type.rs
- docx-wasm/js/index.ts
- docx-wasm/js/table-cell-border.ts
- docx-wasm/js/table-cell-borders.ts
- docx-wasm/js/table-cell.ts
- docx-wasm/src/abstract_numbering.rs
- docx-wasm/src/adaptors/special_indent.rs
- docx-wasm/src/comment.rs
- docx-wasm/src/delete.rs
- docx-wasm/src/doc.rs
- docx-wasm/src/insert.rs
- docx-wasm/src/level.rs
- docx-wasm/src/lib.rs
- docx-wasm/src/numbering.rs
- docx-wasm/src/paragraph.rs
- docx-wasm/src/reader.rs
- docx-wasm/src/run.rs
- docx-wasm/src/table.rs
- docx-wasm/src/table_cell.rs
- docx-wasm/src/table_cell_border.rs
- docx-wasm/src/table_row.rs
> feat: Support table cell border

- docx-wasm/js/index.ts
> fix: expose abstract numbering

- docx-wasm/js/index.ts
- docx-wasm/js/paragraph.ts
- docx-wasm/js/table-cell.ts
- docx-wasm/js/table-row.ts
- docx-wasm/js/table.ts
- docx-wasm/src/doc.rs
> fix: numbering for js

- docx-wasm/package.json
> fix: package.json

- docx-wasm/js/numbering.ts
- docx-wasm/package.json
> fix: 0.0.77

- docx-core/src/types/alignment_type.rs
- docx-wasm/js/index.ts
- docx-wasm/js/paragraph.ts
> fix: Add end and distribute

- docx-core/src/reader/ignore.rs
- docx-core/src/reader/mod.rs
- docx-core/src/reader/paragraph.rs
- docx-core/src/reader/table.rs
- docx-core/src/reader/table_cell.rs
- docx-core/src/reader/table_row.rs
- docx-core/src/reader/xml_element.rs
> fix: ignore change property to import diff docx

- docx-core/src/reader/attributes/indent.rs
- docx-core/src/reader/errors.rs
> fix: size reader

- docx-core/examples/bookmark.rs
- docx-core/src/documents/document.rs
- docx-core/src/documents/mod.rs
- docx-wasm/example/index.ts
- docx-wasm/js/index.ts
- docx-wasm/src/doc.rs
Add top level bookmark
NA
NA
NA
> feat: Support top level bookmark

- docx-core/src/reader/attributes/width.rs
fixed a bug to read width.
NA
NA
NA
> fix: width reader

- .github/workflows/ci.yml
- Cargo.lock
- docx-wasm/Cargo.toml
- docx-wasm/package.json
> add workflow

- docx-core/src/documents/elements/table.rs
- docx-core/src/documents/elements/table_cell_margins.rs
- docx-core/src/documents/elements/table_property.rs
- docx-wasm/js/index.ts
- docx-wasm/js/table.ts
- docx-wasm/package.json
- docx-wasm/src/table.rs
> fix: cell margin to 24

- docx-core/examples/reader.rs
- docx-core/src/reader/style.rs
> fix: style run props bool value

- .github/workflows/ci.yml
- docx-wasm/js/index.ts
- docx-wasm/package.json
> fix: tsc erropr

- docx-core/src/documents/settings.rs
- docx-core/src/xml_builder/elements.rs
> feat: Add word compat to settings

- Cargo.lock
- docx-core/Cargo.toml
- docx-core/src/documents/settings.rs
- docx-core/src/xml_builder/elements.rs
- docx-wasm/package.json
> fix: settings

- Cargo.lock
- docx-core/src/documents/elements/table_row_property.rs
- docx-core/src/xml_builder/elements.rs
- docx-wasm/js/index.ts
- docx-wasm/js/table-row.ts
- docx-wasm/package.json
- docx-wasm/src/table_row.rs
> fix: Add rowHeight func

- docx-core/src/documents/elements/run.rs
- docx-core/src/documents/elements/run_property.rs
- docx-core/src/reader/run_property.rs
- docx-core/src/types/spacing.rs
- docx-wasm/package.json
- docx-wasm/src/run.rs
> Fix spacing

- docx-wasm/package.json
> chore: update version

- docx-wasm/js/json/styles.ts
- docx-wasm/package.json
> Fix json type

- docx-wasm/js/json/comment.ts
> fix: json type

- docx-core/src/documents/document.rs
- docx-core/src/reader/document.rs
- docx-core/src/reader/paragraph.rs
- docx-wasm/js/json/document.ts
- docx-wasm/package.json
- docx-wasm/test/index.test.js
> Fix comment rw

- .github/workflows/ci.yml
- docx-core/src/documents/elements/insert.rs
- docx-core/src/documents/mod.rs
- docx-core/src/reader/insert.rs
- docx-wasm/js/json/paragraph.ts
- docx-wasm/package.json
> fix: read comment in ins

- docx-core/Cargo.toml
> Fix a typo

- docx-core/src/reader/table_cell.rs
- docx-wasm/package.json
> fix: ignore nested table

- docx-wasm/js/json/index.ts
- docx-wasm/package.json
> Expose settings json

- docx-core/src/documents/webextension.rs
- docx-wasm/package.json
- docx-wasm/test/__snapshots__/index.test.js.snap
- docx-wasm/test/index.test.js
> Improve web props

- docx-core/src/reader/comments_extended.rs
- docx-wasm/package.json
> Fix duplicated extended

- docx-wasm/js/json/paragraph.ts
> Fix wrong property name of InsertJSON and DeleteJSON

- CHANGELOG.md
- README.md
- docx-wasm/js/json/line_spacing.ts
- docx-wasm/package.json
> Improve line spacing json

- docx-core/src/documents/document_rels.rs
- docx-wasm/test/__snapshots__/index.test.js.snap
> fix: remove unused rel

- README.md
- docx-wasm/js/footer.ts
- docx-wasm/js/header.ts
- docx-wasm/js/index.ts
- docx-wasm/test/__snapshots__/index.test.js.snap
- docx-wasm/test/index.test.js
impl header/footer API for JS.
NA
NA
NA
> fix: Add test and support table

- CHANGELOG.md
- Cargo.lock
- docx-core/Cargo.toml
> chore: 0.3.2

- docx-core/src/documents/elements/instr_toc.rs
- docx-wasm/test/__snapshots__/index.test.js.snap
Add some options for ToC writer.
NA
NA
NA
> fix: Some options for toc writer

- docx-core/examples/toc_simple.rs
- docx-core/examples/toc_with_style_level.rs
- docx-core/src/documents/elements/table_of_contents.rs
- docx-core/src/documents/mod.rs
- docx-wasm/js/style.ts
- docx-wasm/js/table-of-contents.ts
- docx-wasm/src/style.rs
- docx-wasm/src/table_of_contents.rs
> Support style with levels

- docx-core/src/documents/elements/paragraph.rs
- docx-core/src/documents/elements/paragraph_property_change.rs
- docx-wasm/js/index.ts
- docx-wasm/js/level.ts
- docx-wasm/js/paragraph-property.ts
- docx-wasm/js/paragraph.ts
- docx-wasm/js/run.ts
- docx-wasm/js/style.ts
- docx-wasm/src/paragraph.rs
- docx-wasm/test/__snapshots__/index.test.js.snap
- docx-wasm/test/index.test.js
> fix: js ppr change if

- CHANGELOG.md
- docx-wasm/package.json
> fix: change log

- docx-core/src/documents/elements/table_row.rs
- docx-core/src/documents/elements/table_row_property.rs
- docx-core/src/reader/table_row.rs
- docx-wasm/js/index.ts
- docx-wasm/js/json/table.ts
- docx-wasm/js/table-row.ts
- docx-wasm/src/table_row.rs
> Add table row del

- .gitignore
- Cargo.lock
- docx-core/Cargo.toml
- docx-core/bindings/FontGroup.ts
- docx-core/bindings/FontScheme.ts
- docx-core/bindings/FontSchemeFont.ts
- docx-core/bindings/Theme.ts
- docx-core/src/documents/elements/font_scheme.rs
- docx-core/src/documents/theme.rs
- docx-wasm/js/json/bindings/FontGroup.ts
- docx-wasm/js/json/bindings/FontScheme.ts
- docx-wasm/js/json/bindings/FontSchemeFont.ts
- docx-wasm/js/json/bindings/Theme.ts
- docx-wasm/js/json/index.ts
- docx-wasm/package.json
generate theme bindings by ts_rs
NA
NA
NA
> gen bindings

- CHANGELOG.md
- docx-core/src/documents/elements/table_row.rs
- docx-core/src/documents/elements/table_row_property.rs
- docx-core/src/reader/table_row.rs
- docx-wasm/js/index.ts
- docx-wasm/js/json/table.ts
- docx-wasm/js/table-row.ts
- docx-wasm/package.json
- docx-wasm/src/table_row.rs
> Support table row ins

- docx-core/examples/reader.rs
- docx-core/src/documents/elements/run.rs
> fix: remove \n in text

- docx-core/src/documents/mod.rs
- docx-core/src/reader/run.rs
- docx-core/src/reader/xml_element.rs
- docx-wasm/test/__snapshots__/index.test.js.snap
- docx-wasm/test/index.test.js
> fix: image writer with review

- docx-core/src/documents/elements/doc_grid.rs
- docx-core/src/reader/doc_grid.rs
- docx-core/src/xml_builder/elements.rs
- docx-wasm/src/doc.rs
Fix charspace type. this is because charspace allows negative value.
NA
NA
NA
> fix: chaespace type

- Cargo.lock
- docx-core/src/documents/mod.rs
- docx-core/src/reader/paragraph.rs
- docx-core/src/reader/table_cell.rs
- docx-wasm/Cargo.toml
- docx-wasm/package.json
- docx-wasm/src/doc.rs
> Fix image reader

- docx-core/src/reader/level_override.rs
- docx-core/src/reader/numberings.rs
- docx-wasm/package.json
> fix: level reader

- docx-core/examples/image_inline_rotate.rs
- docx-core/src/documents/elements/drawing.rs
- docx-core/src/documents/elements/pic.rs
- docx-core/src/xml_builder/pic.rs
- docx-wasm/js/image.ts
- docx-wasm/js/index.ts
- docx-wasm/js/json/bindings/Pic.ts
- docx-wasm/src/pic.rs
support `rotate` for pic
see example `inline_image_rotatee`
NA
NA
> feat: support rot

- CHANGELOG.md
- Cargo.lock
- docx-core/Cargo.toml
> fix: changelog

- docx-core/src/documents/document_rels.rs
- docx-wasm/package.json
> fix: escape url

- docx-wasm/js/json/paragraph.ts
- docx-wasm/js/json/run.ts
> refactor: define type instead of IndexAccessType

- CHANGELOG.md
- docx-wasm/package.json
> 0.0.276-rc27

- docx-wasm/js/json/table.ts
> fix: missing replace json types IndexAccessType

- CHANGELOG.md
- docx-core/src/reader/styles.rs
- docx-wasm/js/json/table.ts
- docx-wasm/package.json
> fix: types

- docx-wasm/js/json/line_spacing.ts
> fix: line spacing type

- CHANGELOG.md
- docx-wasm/js/index.ts
- docx-wasm/js/section-property.ts
- docx-wasm/js/settings.ts
- docx-wasm/package.json
> fix: js adjust line table settings

- CHANGELOG.md
- docx-core/examples/reader.rs
- docx-core/src/reader/attributes/width.rs
- docx-wasm/package.json
> [#584] fix: remove %

- CHANGELOG.md
- docx-core/src/documents/elements/instr_toc.rs
- docx-core/src/documents/elements/structured_data_tag.rs
- docx-core/src/documents/elements/table_of_contents.rs
- docx-core/src/errors/mod.rs
- docx-wasm/js/comment.ts
- docx-wasm/js/delete.ts
- docx-wasm/js/hyperlink.ts
- docx-wasm/js/index.ts
- docx-wasm/js/insert.ts
- docx-wasm/js/paragraph.ts
- docx-wasm/js/run.ts
- docx-wasm/js/table-cell.ts
- docx-wasm/js/table-of-contents.ts
- docx-wasm/js/table.ts
- docx-wasm/package.json
- docx-wasm/src/table_of_contents.rs
- docx-wasm/test/index.test.js
> fix: add before/after contents and with_instr_text in toc

- CHANGELOG.md
- docx-core/src/documents/elements/paragraph_property.rs
- docx-wasm/js/paragraph-property.ts
- docx-wasm/js/paragraph.ts
- docx-wasm/js/style.ts
- docx-wasm/package.json
- docx-wasm/src/paragraph.rs
expose outline level setter for paragraph
> fix: expose outline level

- docx-core/src/documents/elements/table_of_contents.rs
- docx-wasm/package.json
> fix: after contents in toc

- docx-core/src/documents/elements/style.rs
> fix: duplicated based on

- docx-wasm/js/builder.ts
- docx-wasm/js/comment.ts
- docx-wasm/js/hyperlink.ts
- docx-wasm/js/index.ts
- docx-wasm/js/paragraph.ts
- docx-wasm/js/table-cell.ts
- docx-wasm/js/table-of-contents.ts
- fix circular reference when using module that built with esbuild
> fix: circular reference when using module that built with esbuild

- docx-wasm/package.json
> 0.0.277-rc4

- docx-core/examples/toc_with_comment.rs
- docx-core/src/documents/elements/structured_data_tag.rs
- docx-core/src/documents/elements/table_cell.rs
- docx-core/src/documents/elements/table_of_contents.rs
- docx-core/src/documents/mod.rs
- docx-core/src/reader/table_cell.rs
- docx-wasm/js/json/table.ts
- docx-wasm/js/table-cell.ts
- docx-wasm/js/table-of-contents.ts
- docx-wasm/package.json
- docx-wasm/src/table_cell.rs
- docx-wasm/src/table_of_contents.rs
> fix: read sdt in cell

- CHANGELOG.md
- docx-core/src/documents/elements/link.rs
- docx-wasm/package.json
> fix: link output

- CHANGELOG.md
- docx-wasm/js/paragraph-property.ts
- docx-wasm/js/paragraph.ts
- docx-wasm/package.json
- docx-wasm/src/paragraph.rs
> Support indent right

- CHANGELOG.md
- docx-wasm/js/index.ts
- docx-wasm/package.json
> fix: add missing if

- CHANGELOG.md
- docx-wasm/js/json/section-property.ts
- docx-wasm/package.json
> Make doc grid optional

- CHANGELOG.md
- docx-core/src/reader/attributes/border.rs
- docx-core/src/reader/attributes/indent.rs
- docx-core/src/reader/attributes/line_spacing.rs
- docx-core/src/reader/drawing.rs
- docx-core/src/reader/pic.rs
- docx-core/src/reader/run_property.rs
- docx-wasm/package.json
> fix: number type

- docx-core/src/documents/elements/delete.rs
- docx-core/src/documents/elements/insert.rs
- docx-wasm/package.json
> Escape author

- CHANGELOG.md
- docx-core/src/documents/elements/paragraph_property_change.rs
- docx-core/src/documents/elements/table_of_contents.rs
- docx-wasm/package.json
- docx-wasm/src/delete.rs
- docx-wasm/src/insert.rs
> fix: escape

- docx-wasm/package.json
> 0.0.278-rc24

- docx-wasm/js/json/styles.ts
- docx-wasm/js/json/table.ts
> fix: json types

- CHANGELOG.md
- docx-wasm/package.json
> chore: rc27

- docx-core/src/documents/elements/instr_hyperlink.rs
- docx-core/src/documents/elements/instr_tc.rs
- docx-core/src/documents/elements/instr_toc.rs
> fix: some clippy

- docx-core/src/reader/errors.rs
- docx-core/src/reader/header_or_footer_rels.rs
- docx-core/src/reader/mod.rs
- docx-core/src/reader/rels.rs
close https://github.com/bokuweb/docx-rs/issues/608
NA
NA
NA
> Read header and footer image

- docx-core/src/documents/mod.rs
- docx-wasm/package.json
> Fix header footer rels order

- docx-core/src/documents/elements/page_num.rs
- docx-core/src/types/alignment_type.rs
- docx-wasm/js/json/bindings/AlignmentType.ts
- docx-wasm/js/json/paragraph.ts
- docx-wasm/package.json
> fix: frame pr

- CHANGELOG.md
- docx-core/src/documents/elements/page_num.rs
- docx-wasm/js/page-num.ts
- docx-wasm/js/paragraph-property.ts
- docx-wasm/package.json
- docx-wasm/src/page_num.rs
- docx-wasm/test/index.test.js
> Fix frame property

- README.md
> Update README.md: Fix NodeJS example

- docx-core/src/reader/document_rels.rs
- docx-core/src/reader/header_or_footer_rels.rs
- docx-core/src/reader/rels.rs
> fix: use btree set

- docx-wasm/js/json/bindings/PositionalTab.ts
- docx-wasm/js/json/bindings/PositionalTabAlignmentType.ts
- docx-wasm/js/json/bindings/PositionalTabRelativeTo.ts
- docx-wasm/package.json
> chore: 0.4.18-rc3

- docx-wasm/package.json
> 0.4.18-rc4

- docx-core/src/documents/elements/run_fonts.rs
> fix: escape font

- docx-core/src/documents/elements/paragraph.rs
- docx-wasm/js/paragraph-property.ts
- docx-wasm/js/paragraph.ts
- docx-wasm/src/paragraph.rs
Support paragraph.color
NA
NA
NA
> feat: Support paragraph color

- docx-core/src/documents/mod.rs
- docx-wasm/js/index.ts
- docx-wasm/src/doc.rs
expose comments_json for internal useage
NA
NA
NA
> feat: add comments_json

- docx-wasm/package.json
> chore: published

- docx-core/src/documents/elements/based_on.rs
- docx-core/src/documents/elements/link.rs
- docx-core/src/documents/elements/paragraph_style.rs
- docx-core/src/documents/elements/run_style.rs
- docx-core/src/documents/elements/style.rs
- docx-wasm/package.json
> Escape style name

- docx-core/src/documents/elements/based_on.rs
- docx-core/src/documents/elements/link.rs
- docx-core/src/documents/elements/paragraph_style.rs
- docx-core/src/documents/elements/run_style.rs
- docx-core/src/documents/elements/style.rs
- docx-wasm/package.json
> fix: escape some feild

- Cargo.lock
- docx-core/Cargo.toml
- docx-wasm/package.json
> chore: rc19

- docx-wasm/js/index.ts
- docx-wasm/package.json
> Fix level char spacing

- docx-core/src/documents/elements/instr_tc.rs
- docx-wasm/package.json
- docx-wasm/src/run.rs
- docx-wasm/test/index.test.js
> fix: escape tc text

- docx-core/src/documents/elements/paragraph.rs
- docx-core/src/documents/elements/table_of_contents.rs
- docx-wasm/js/paragraph-property.ts
- docx-wasm/js/paragraph.ts
- docx-wasm/package.json
- docx-wasm/test/index.test.js
> Support snaptogrid

- docx-core/src/documents/elements/style.rs
- docx-core/src/documents/preset_styles/toc.rs
- docx-wasm/js/style.ts
- docx-wasm/package.json
> fix: snap to grid for style

- docx-core/src/documents/elements/style.rs
- docx-core/src/documents/preset_styles/toc.rs
- docx-wasm/package.json
> Add after for toc styles

- docx-core/src/reader/run_property.rs
- docx-wasm/js/json/run.ts
- docx-wasm/js/run-property.ts
- docx-wasm/js/run.ts
- docx-wasm/package.json
- docx-wasm/src/run.rs
- docx-wasm/src/run_property.rs
- docx-wasm/src/style.rs
- docx-wasm/test/index.test.js
> feat: add shd for run

- docx-core/src/documents/elements/bold.rs
- docx-core/src/documents/elements/dstrike.rs
- docx-core/src/documents/elements/italic.rs
- docx-core/src/documents/elements/strike.rs
- docx-core/src/xml_builder/elements.rs
> fix: disable bool el

- docx-wasm/package.json
> 0.4.18-rc45

- CHANGELOG.md
- docx-core/src/documents/document.rs
- docx-core/src/documents/mod.rs
- docx-wasm/js/index.ts
- docx-wasm/js/section-property.ts
- docx-wasm/package.json
- docx-wasm/src/doc.rs
> Add titlepg

- .github/workflows/ci.yml
> Update ci.yml to use reg-cli v3

- docx-core/src/documents/elements/paragraph.rs
- docx-core/src/documents/elements/table_of_contents.rs
> Revert "Regen paraid"
